import { sub } from 'date-fns'
import type { Issue, User } from './types'

export const users: User[] = [
  {
    id: 'a1b2c3d4e5f6g7h8i9j0k',
    name: 'John Smith',
    picture: '/avatars/john-smith.png',
  },
  {
    id: 'b2c3d4e5f6g7h8i9j0k1l',
    name: 'Rose Eve',
    picture: '/avatars/rose-eve.png',
  },
  {
    id: 'c3d4e5f6g7h8i9j0k1l2m',
    name: 'Adam Young',
    picture: '/avatars/adam-young.png',
  },
  {
    id: 'd4e5f6g7h8i9j0k1l2m3n',
    name: 'Michael Scott',
    picture: '/avatars/michael-scott.png',
  },
]

export const issues: Issue[] = [
  {
    id: 'e5f6g7h8i9j0k1l2m3n4o',
    title: 'Implement user login',
    status: 'in-progress',
    assignee: users.find((u) => u.name === 'John Smith')!,
    startDate: sub(new Date(), { days: 3 }),
    estimatedHours: 101,
    labelIds: ['feature'],
  },
  {
    id: 'f6g7h8i9j0k1l2m3n4o5p',
    title: 'Fix payment processing',
    status: 'todo',
    assignee: users.find((u) => u.name === 'Rose Eve')!,
    estimatedHours: 6,
    labelIds: ['bug'],
  },
  {
    id: 'g7h8i9j0k1l2m3n4o5p6q',
    title: 'Design database schema',
    status: 'done',
    assignee: users.find((u) => u.name === 'Adam Young')!,
    startDate: sub(new Date(), { days: 7 }),
    endDate: sub(new Date(), { days: 2 }),
    estimatedHours: 10,
    labelIds: ['database', 'feature'],
  },
  {
    id: 'h8i9j0k1l2m3n4o5p6q7r',
    title: 'Update API docs',
    status: 'backlog',
    estimatedHours: 4,
    labelIds: ['docs', 'api'],
  },
  {
    id: 'i9j0k1l2m3n4o5p6q7r8s',
    title: 'Optimize frontend',
    status: 'in-progress',
    assignee: users.find((u) => u.name === 'Michael Scott')!,
    startDate: sub(new Date(), { days: 2 }),
    estimatedHours: 12,
    labelIds: ['performance', 'ui'],
  },
  {
    id: 'j0k1l2m3n4o5p6q7r8s9t',
    title: 'Add unit tests',
    status: 'todo',
    assignee: users.find((u) => u.name === 'John Smith')!,
    estimatedHours: 8,
    labelIds: ['testing', 'feature'],
  },
  {
    id: 'k1l2m3n4o5p6q7r8s9t0u',
    title: 'Implement dark mode',
    status: 'done',
    startDate: sub(new Date(), { days: 5 }),
    endDate: sub(new Date(), { hours: 12 }),
    estimatedHours: 6,
    labelIds: ['feature', 'ui'],
  },
  {
    id: 'l2m3n4o5p6q7r8s9t0u1v',
    title: 'Fix search filter',
    status: 'backlog',
    estimatedHours: 3,
    labelIds: ['bug', 'ui'],
  },
  {
    id: 'm3n4o5p6q7r8s9t0u1v2w',
    title: 'Refactor auth middleware',
    status: 'todo',
    assignee: users.find((u) => u.name === 'Rose Eve')!,
    estimatedHours: 5,
    labelIds: ['refactor'],
  },
  {
    id: 'n4o5p6q7r8s9t0u1v2w3x',
    title: 'Update user profiles',
    status: 'in-progress',
    assignee: users.find((u) => u.name === 'Adam Young')!,
    startDate: sub(new Date(), { days: 4 }),
    estimatedHours: 7,
    labelIds: ['enhancement', 'ui'],
  },
  {
    id: 'o5p6q7r8s9t0u1v2w3x4y',
    title: 'Add error logging',
    status: 'done',
    assignee: users.find((u) => u.name === 'Michael Scott')!,
    startDate: sub(new Date(), { days: 6 }),
    endDate: sub(new Date(), { days: 1 }),
    estimatedHours: 4,
    labelIds: ['feature'],
  },
  {
    id: 'p6q7r8s9t0u1v2w3x4y5z',
    title: 'Improve form validation',
    status: 'backlog',
    estimatedHours: 5,
    labelIds: ['enhancement', 'ui'],
  },
  {
    id: 'q7r8s9t0u1v2w3x4y5z6a',
    title: 'Setup CI/CD pipeline',
    status: 'todo',
    assignee: users.find((u) => u.name === 'John Smith')!,
    estimatedHours: 10,
    labelIds: ['feature'],
  },
  {
    id: 'r8s9t0u1v2w3x4y5z6a7b',
    title: 'Fix mobile layout',
    status: 'in-progress',
    assignee: users.find((u) => u.name === 'Rose Eve')!,
    startDate: sub(new Date(), { days: 1 }),
    estimatedHours: 6,
    labelIds: ['bug', 'ui'],
  },
  {
    id: 's9t0u1v2w3x4y5z6a7b8c',
    title: 'Add notifications',
    status: 'done',
    startDate: sub(new Date(), { days: 8 }),
    endDate: sub(new Date(), { days: 3 }),
    estimatedHours: 8,
    labelIds: ['feature', 'ui'],
  },
  {
    id: 't0u1v2w3x4y5z6a7b8c9d',
    title: 'Optimize database queries',
    status: 'backlog',
    estimatedHours: 7,
    labelIds: ['performance', 'database'],
  },
  {
    id: 'u1v2w3x4y5z6a7b8c9d0e',
    title: 'Update security headers',
    status: 'todo',
    assignee: users.find((u) => u.name === 'Adam Young')!,
    estimatedHours: 3,
    labelIds: ['security'],
  },
  {
    id: 'v2w3x4y5z6a7b8c9d0e1f',
    title: 'Implement caching',
    status: 'in-progress',
    assignee: users.find((u) => u.name === 'Michael Scott')!,
    startDate: sub(new Date(), { days: 2 }),
    estimatedHours: 9,
    labelIds: ['performance', 'feature'],
  },
  {
    id: 'w3x4y5z6a7b8c9d0e1f2g',
    title: 'Fix login redirect',
    status: 'done',
    assignee: users.find((u) => u.name === 'John Smith')!,
    startDate: sub(new Date(), { days: 4 }),
    endDate: sub(new Date(), { hours: 6 }),
    estimatedHours: 4,
    labelIds: ['bug'],
  },
  {
    id: 'x4y5z6a7b8c9d0e1f2g3h',
    title: 'Add analytics tracking',
    status: 'backlog',
    estimatedHours: 6,
    labelIds: ['feature'],
  },
  {
    id: 'y5z6a7b8c9d0e1f2g3h4i',
    title: 'Update payment UI',
    status: 'todo',
    assignee: users.find((u) => u.name === 'Rose Eve')!,
    estimatedHours: 5,
    labelIds: ['ui', 'enhancement'],
  },
  {
    id: 'z6a7b8c9d0e1f2g3h4i5j',
    title: 'Refactor API routes',
    status: 'in-progress',
    assignee: users.find((u) => u.name === 'Adam Young')!,
    startDate: sub(new Date(), { days: 3 }),
    estimatedHours: 8,
    labelIds: ['refactor', 'api'],
  },
  {
    id: 'a7b8c9d0e1f2g3h4i5j6k',
    title: 'Fix image upload',
    status: 'done',
    startDate: sub(new Date(), { days: 6 }),
    endDate: sub(new Date(), { days: 2 }),
    estimatedHours: 5,
    labelIds: ['bug'],
  },
  {
    id: 'b8c9d0e1f2g3h4i5j6k7l',
    title: 'Add password reset',
    status: 'backlog',
    estimatedHours: 4,
    labelIds: ['feature'],
  },
  {
    id: 'c9d0e1f2g3h4i5j6k7l8m',
    title: 'Update dashboard',
    status: 'todo',
    assignee: users.find((u) => u.name === 'Michael Scott')!,
    estimatedHours: 7,
    labelIds: ['ui', 'enhancement'],
  },
  {
    id: 'd0e1f2g3h4i5j6k7l8m9n',
    title: 'Optimize image loading',
    status: 'in-progress',
    assignee: users.find((u) => u.name === 'John Smith')!,
    startDate: sub(new Date(), { days: 1 }),
    estimatedHours: 6,
    labelIds: ['performance', 'ui'],
  },
  {
    id: 'e1f2g3h4i5j6k7l8m9n0o',
    title: 'Fix email templates',
    status: 'done',
    assignee: users.find((u) => u.name === 'Rose Eve')!,
    startDate: sub(new Date(), { days: 5 }),
    endDate: sub(new Date(), { days: 1 }),
    estimatedHours: 3,
    labelIds: ['bug', 'ui'],
  },
  {
    id: 'f2g3h4i5j6k7l8m9n0o1p',
    title: 'Add user roles',
    status: 'backlog',
    estimatedHours: 8,
    labelIds: ['feature'],
  },
  {
    id: 'g3h4i5j6k7l8m9n0o1p2q',
    title: 'Update checkout flow',
    status: 'todo',
    assignee: users.find((u) => u.name === 'Adam Young')!,
    estimatedHours: 6,
    labelIds: ['enhancement', 'ui'],
  },
  {
    id: 'h4i5j6k7l8m9n0o1p2q3r',
    title: 'Fix navigation bar',
    status: 'in-progress',
    assignee: users.find((u) => u.name === 'Michael Scott')!,
    startDate: sub(new Date(), { days: 2 }),
    estimatedHours: 4,
    labelIds: ['bug', 'ui'],
  },
  {
    id: 'i5j6k7l8m9n0o1p2q3r4s',
    title: 'Add loading states',
    status: 'done',
    startDate: sub(new Date(), { days: 7 }),
    endDate: sub(new Date(), { days: 3 }),
    estimatedHours: 5,
    labelIds: ['feature', 'ui'],
  },
  {
    id: 'j6k7l8m9n0o1p2q3r4s5t',
    title: 'Optimize API calls',
    status: 'backlog',
    estimatedHours: 7,
    labelIds: ['performance', 'api'],
  },
  {
    id: 'k7l8m9n0o1p2q3r4s5t6u',
    title: 'Update signup form',
    status: 'todo',
    assignee: users.find((u) => u.name === 'John Smith')!,
    estimatedHours: 4,
    labelIds: ['enhancement', 'ui'],
  },
  {
    id: 'l8m9n0o1p2q3r4s5t6u7v',
    title: 'Fix profile edit',
    status: 'in-progress',
    assignee: users.find((u) => u.name === 'Rose Eve')!,
    startDate: sub(new Date(), { days: 1 }),
    estimatedHours: 6,
    labelIds: ['bug', 'ui'],
  },
  {
    id: 'm9n0o1p2q3r4s5t6u7v8w',
    title: 'Add data export',
    status: 'done',
    assignee: users.find((u) => u.name === 'Adam Young')!,
    startDate: sub(new Date(), { days: 4 }),
    endDate: sub(new Date(), { hours: 12 }),
    estimatedHours: 8,
    labelIds: ['feature'],
  },
  {
    id: 'n0o1p2q3r4s5t6u7v8w9x',
    title: 'Update footer links',
    status: 'backlog',
    estimatedHours: 3,
    labelIds: ['enhancement', 'ui'],
  },
  {
    id: 'o1p2q3r4s5t6u7v8w9x0y',
    title: 'Fix search results',
    status: 'todo',
    assignee: users.find((u) => u.name === 'Michael Scott')!,
    estimatedHours: 5,
    labelIds: ['bug', 'ui'],
  },
  {
    id: 'p2q3r4s5t6u7v8w9x0y1z',
    title: 'Add session timeout',
    status: 'in-progress',
    assignee: users.find((u) => u.name === 'John Smith')!,
    startDate: sub(new Date(), { days: 3 }),
    estimatedHours: 7,
    labelIds: ['feature', 'security'],
  },
  {
    id: 'q3r4s5t6u7v8w9x0y1z2a',
    title: 'Update terms page',
    status: 'done',
    startDate: sub(new Date(), { days: 6 }),
    endDate: sub(new Date(), { days: 2 }),
    estimatedHours: 4,
    labelIds: ['docs'],
  },
  {
    id: 'r4s5t6u7v8w9x0y1z2a3b',
    title: 'Fix dropdown menu',
    status: 'backlog',
    estimatedHours: 3,
    labelIds: ['bug', 'ui'],
  },
  {
    id: 's5t6u7v8w9x0y1z2a3b4c',
    title: 'Add input validation',
    status: 'todo',
    assignee: users.find((u) => u.name === 'Rose Eve')!,
    estimatedHours: 6,
    labelIds: ['feature', 'ui'],
  },
  {
    id: 't6u7v8w9x0y1z2a3b4c5d',
    title: 'Optimize CSS',
    status: 'in-progress',
    assignee: users.find((u) => u.name === 'Adam Young')!,
    startDate: sub(new Date(), { days: 2 }),
    estimatedHours: 5,
    labelIds: ['performance', 'ui'],
  },
  {
    id: 'u7v8w9x0y1z2a3b4c5d6e',
    title: 'Fix logout bug',
    status: 'done',
    assignee: users.find((u) => u.name === 'Michael Scott')!,
    startDate: sub(new Date(), { days: 5 }),
    endDate: sub(new Date(), { days: 1 }),
    estimatedHours: 4,
    labelIds: ['bug'],
  },
  {
    id: 'v8w9x0y1z2a3b4c5d6e7f',
    title: 'Add breadcrumbs',
    status: 'backlog',
    estimatedHours: 5,
    labelIds: ['feature', 'ui'],
  },
  {
    id: 'w9x0y1z2a3b4c5d6e7f8g',
    title: 'Update pricing page',
    status: 'todo',
    assignee: users.find((u) => u.name === 'John Smith')!,
    estimatedHours: 6,
    labelIds: ['enhancement', 'ui'],
  },
  {
    id: 'x0y1z2a3b4c5d6e7f8g9h',
    title: 'Fix table sorting',
    status: 'in-progress',
    assignee: users.find((u) => u.name === 'Rose Eve')!,
    startDate: sub(new Date(), { days: 1 }),
    estimatedHours: 4,
    labelIds: ['bug', 'ui'],
  },
  {
    id: 'y1z2a3b4c5d6e7f8g9h0i',
    title: 'Add file upload',
    status: 'done',
    startDate: sub(new Date(), { days: 7 }),
    endDate: sub(new Date(), { days: 3 }),
    estimatedHours: 7,
    labelIds: ['feature'],
  },
  {
    id: 'z2a3b4c5d6e7f8g9h0i1j',
    title: 'Optimize JS bundle',
    status: 'backlog',
    estimatedHours: 8,
    labelIds: ['performance'],
  },
  {
    id: 'a3b4c5d6e7f8g9h0i1j2k',
    title: 'Update contact form',
    status: 'todo',
    assignee: users.find((u) => u.name === 'Adam Young')!,
    estimatedHours: 5,
    labelIds: ['enhancement', 'ui'],
  },
]
